client.tibiadata.name=TibiaData
client.tibiadata.host=https://api.tibiadata.com
client.tibiadata.endpoint.character=/v4/character/{caracterName}
client.tibiadata.endpoint.world=/v4/world/{world}
feign.client.config.default.loggerLevel = full
logging.level.com.tibia.api = DEBUG